// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDApry5SkJs2Kijolt0aWcIdAkZcTYS8Yw',
    appId: '1:655800968576:web:046fcec8878db88c434d65',
    messagingSenderId: '655800968576',
    projectId: 'trialchatapp-8a29b',
    authDomain: 'trialchatapp-8a29b.firebaseapp.com',
    databaseURL: 'https://trialchatapp-8a29b-default-rtdb.firebaseio.com',
    storageBucket: 'trialchatapp-8a29b.appspot.com',
    measurementId: 'G-E1G2KYP1LK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBwi1WMLaIcvyLmLouThfGqxLEaebsW7k',
    appId: '1:655800968576:android:a310e54632687233434d65',
    messagingSenderId: '655800968576',
    projectId: 'trialchatapp-8a29b',
    databaseURL: 'https://trialchatapp-8a29b-default-rtdb.firebaseio.com',
    storageBucket: 'trialchatapp-8a29b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaKtZQ7iJcypGwLPcZGeX7Ay1vP7om6RQ',
    appId: '1:655800968576:ios:410ece96e06a0b6d434d65',
    messagingSenderId: '655800968576',
    projectId: 'trialchatapp-8a29b',
    databaseURL: 'https://trialchatapp-8a29b-default-rtdb.firebaseio.com',
    storageBucket: 'trialchatapp-8a29b.appspot.com',
    iosClientId: '655800968576-dto1j2oc1dre3p3lvaop527n3iohmbrc.apps.googleusercontent.com',
    iosBundleId: 'com.example.ebookApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaKtZQ7iJcypGwLPcZGeX7Ay1vP7om6RQ',
    appId: '1:655800968576:ios:410ece96e06a0b6d434d65',
    messagingSenderId: '655800968576',
    projectId: 'trialchatapp-8a29b',
    databaseURL: 'https://trialchatapp-8a29b-default-rtdb.firebaseio.com',
    storageBucket: 'trialchatapp-8a29b.appspot.com',
    iosClientId: '655800968576-dto1j2oc1dre3p3lvaop527n3iohmbrc.apps.googleusercontent.com',
    iosBundleId: 'com.example.ebookApp',
  );
}
